find_house_proj/admin_panel_app/urls.py
from django.urls import path
from admin_panel_app import views

app_name = 'admin_panel_app'

urlpatterns = [
    # Admin Home URLs
    path('', views.AdminPanelHomeView.as_view(), name='admin_index'),
    
    # Admin Users URLs
    path('users-list/', views.UserListView.as_view(), name='admin_user_list_index'),
    path('users-details/<int:pk>/', views.UserDetailView.as_view(), name='admin_user_read'),
    path('user/delete/<int:pk>/', views.UserDeleteView.as_view(), name='admin_user_delete'),
    path('user/add/', views.UserCreateView.as_view(), name='admin_user_create'),
    path('user/edit/<int:pk>/', views.UserUpdateView.as_view(), name='admin_user_update'),
    
    # Admin Announcements URLs
    path('announcements-list/', views.AnnouncementListView.as_view(), name='admin_announcement_list'),
    path('announcement/delete/<int:pk>/', views.AnnouncementDeleteView.as_view(), name='admin_announcement_delete'),
    path('announcement/add/', views.AnnouncementCreateView.as_view(), name='admin_announcement_create'),
    path('announcement/edit/<int:pk>/', views.AnnouncementUpdateView.as_view(), name='admin_announcement_update'),
    path('announcements-details/<slug:slug>/', views.AnnouncementDetailView.as_view(), name='admin_announcement_read'),
    
    # Admin Announcement Images URLs
    path('announcement-images-list/', views.AnnouncementImageListView.as_view(), name='admin_announcement_images_list'),
    path('announcement-images-details/<int:pk>/', views.AnnouncementImageDetailView.as_view(), name='admin_announcement_images_read'),
    path('announcement-images/delete/<int:pk>/', views.AnnouncementImageDeleteView.as_view(), name='admin_announcement_images_delete'),
    path('announcement-images/add/', views.AnnouncementImageCreateView.as_view(), name='admin_announcement_images_create'),
    path('announcement-images/edit/<int:pk>/', views.AnnouncementImageUpdateView.as_view(), name='admin_announcement_images_update'),
    
    # Admin Categories URLs
    path('categories-list/', views.CategoryListView.as_view(), name='admin_categories_list'),
    path('categories-details/<int:pk>/', views.CategoryDetailView.as_view(), name='admin_category_read'),
    path('category/delete/<int:pk>/', views.CategoryDeleteView.as_view(), name='admin_category_delete'),
    path('category/add/', views.CategoryCreateView.as_view(), name='admin_category_create'),
    path('category/edit/<int:pk>/', views.CategoryUpdateView.as_view(), name='admin_category_update'),
    
    # Admin Favorites URLs
    path('favorites-list/', views.FavoriteListView.as_view(), name='admin_favorites_list'),
    path('favorites-details/<int:pk>/', views.FavoriteDetailView.as_view(), name='admin_favorite_read'),
    path('favorite/delete/<int:pk>/', views.FavoriteDeleteView.as_view(), name='admin_favorite_delete'),
    path('favorite/add/', views.FavoriteCreateView.as_view(), name='admin_favorite_create'),
    path('favorite/edit/<int:pk>/', views.FavoriteUpdateView.as_view(), name='admin_favorite_update'),
    
    # Admin News URLs
    path('news-list/', views.NewsListView.as_view(), name='admin_news_list'),
    path('news/delete/<int:pk>/', views.NewsDeleteView.as_view(), name='admin_news_delete'),
    path('news/add/', views.NewsCreateView.as_view(), name='admin_news_create'),
    path('news/edit/<int:pk>/', views.NewsUpdateView.as_view(), name='admin_news_update'),
    path('news-details/<slug:slug>/', views.NewsDetailView.as_view(), name='admin_news_read'),
    
    # Admin Announcement View Histories URLs
    path('announcement-view-histories-list/', views.AnnouncementViewHistoryListView.as_view(), name='admin_announcement_view_histories_list'),
    path('announcement-view-histories-details/<int:pk>/', views.AnnouncementViewHistoryDetailView.as_view(), name='admin_announcement_view_history_read'),
    path('announcement-view-history/delete/<int:pk>/', views.AnnouncementViewHistoryDeleteView.as_view(), name='admin_announcement_view_history_delete'),
    path('announcement-view-history/add/', views.AnnouncementViewHistoryCreateView.as_view(), name='admin_announcement_view_history_create'),
    path('announcement-view-history/edit/<int:pk>/', views.AnnouncementViewHistoryUpdateView.as_view(), name='admin_announcement_view_history_update'),
    
    # Admin Comments URLs
    path('comments-list/', views.CommentListView.as_view(), name='admin_comments_list'),
    path('comments-details/<int:pk>/', views.CommentDetailView.as_view(), name='admin_comment_read'),
    path('comment/delete/<int:pk>/', views.CommentDeleteView.as_view(), name='admin_comment_delete'),
    path('comment/add/', views.CommentCreateView.as_view(), name='admin_comment_create'),
    path('comment/edit/<int:pk>/', views.CommentUpdateView.as_view(), name='admin_comment_update'),
    
    # Admin Chats URLs
    path('chats-list/', views.ChatListView.as_view(), name='admin_chats_list'),
    path('chats-details/<int:pk>/', views.ChatDetailView.as_view(), name='admin_chat_read'),
    path('chat/delete/<int:pk>/', views.ChatDeleteView.as_view(), name='admin_chat_delete'),
    path('chat/add/', views.ChatCreateView.as_view(), name='admin_chat_create'),
    path('chat/edit/<int:pk>/', views.ChatUpdateView.as_view(), name='admin_chat_update'),
    
    # Admin Messages URLs
    path('messages-list/', views.MessageListView.as_view(), name='admin_messages_list'),
    path('messages-details/<int:pk>/', views.MessageDetailView.as_view(), name='admin_message_read'),
    path('message/delete/<int:pk>/', views.MessageDeleteView.as_view(), name='admin_message_delete'),
    path('message/add/', views.MessageCreateView.as_view(), name='admin_message_create'),
    path('message/edit/<int:pk>/', views.MessageUpdateView.as_view(), name='admin_message_update'),

    # Admin Content URLs
    path('content-list/', views.ContentListView.as_view(), name='admin_content_list'),
    path('content-details/<int:pk>/', views.ContentDetailView.as_view(), name='admin_content_read'),
    path('content/delete/<int:pk>/', views.ContentDeleteView.as_view(), name='admin_content_delete'),
    path('content/add/', views.ContentCreateView.as_view(), name='admin_content_create'),
    path('content/edit/<int:pk>/', views.ContentUpdateView.as_view(), name='admin_content_update'),
]

find_house_proj/chat_app/urls.py
from django.urls import path
from . import views

app_name = 'chat_app'

urlpatterns = [
    # Chat URLs
    path('chats/', views.chat_list, name='chat_list'),
    path('chat/<int:chat_id>/', views.chat_read, name='chat_read'),
    path('chat/create-or-get/<int:other_user_id>/', views.create_or_get_chat, name='create_or_get_chat'),
    path('chat/delete/<int:chat_id>/', views.delete_chat, name='delete_chat'),
    path('chat/<int:chat_id>/edit-message/<int:message_id>/', views.edit_message, name='edit_message'),
]

find_house_proj/find_house_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from find_house_app.views import set_language
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('find_house_app.urls')),
    path('users/', include('users_app.urls')),
    path('admin-panel/', include('admin_panel_app.urls')),
    path('chat/', include('chat_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    *i18n_patterns(*urlpatterns, prefix_default_language=False),
     path("set-language/<str:language>", set_language, name="set_language"),
]

find_house_proj/admin_panel_app/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView, TemplateView
from users_app.models import *
from users_app.forms import *
from find_house_app.models import *
from find_house_app.forms import *
from chat_app.models import *
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import update_session_auth_hash
from admin_panel_app.forms import (UserForm, EditUserForm, AnnouncementForm, AnnouncementImageForm, CategoryForm, FavoriteForm, NewsForm, AnnouncementViewHistoryForm, 
                                   CommentForm, ChatForm, MessageForm)
from django.contrib.auth.hashers import make_password
from admin_panel_app.models import Content
from admin_panel_app.forms import ContentForm
from slugify import slugify

# region Basic views
class AdminPanelHomeView(TemplateView):
    template_name = 'admin_panel_app/index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users_count'] = CustomUser.objects.all().count()
        context['announcements_count'] = Announcement.objects.all().count()
        context['categories_count'] = Category.objects.all().count()
        context['news_count'] = News.objects.all().count()
        context['comments_count'] = Comment.objects.all().count()
        context['chats_count'] = Chat.objects.all().count()
        context['messages_count'] = Message.objects.all().count()
        
        return context
# endregion
    
# region User views
class UserCreateView(CreateView):
    model = CustomUser
    form_class = UserForm
    template_name = 'admin_panel_app/users/create.html'
    success_url = reverse_lazy('admin_panel_app:admin_user_list_index')

    def form_valid(self, form):
        form.instance.password = make_password(form.cleaned_data['password'])

        if form.cleaned_data.get('is_admin'):
            form.instance.is_superuser = True
            form.instance.is_admin = True

        return super().form_valid(form)
    
class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = EditUserForm
    template_name = 'admin_panel_app/users/update.html'
    success_url = reverse_lazy('admin_panel_app:admin_user_list_index')
    
    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(CustomUser, pk=pk)

    def form_valid(self, form):
        password = form.cleaned_data.get('password')
        password2 = form.cleaned_data.get('password2')

        if password and password2:
            user = self.request.user
            if user.check_password(password) and password == password2:
                user.set_password(password)
                user.save()
                update_session_auth_hash(self.request, user)
            else:
                pass
        
        response = super().form_valid(form)
        return response

class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = CustomUser
    template_name = 'admin_panel_app/users/delete.html'
    context_object_name = 'user'
    success_url = reverse_lazy('admin_panel_app:admin_user_list_index')

class UserDetailView(LoginRequiredMixin, DetailView):
    model = CustomUser
    template_name = 'admin_panel_app/users/read.html'
    context_object_name = 'user'

class UserListView(LoginRequiredMixin, ListView):
    model = CustomUser
    template_name = 'admin_panel_app/users/list.html'
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = CustomUser.objects.all().order_by('pk')
                
        return context
# endregion

 # region Announcement views
class AnnouncementCreateView(CreateView):
    model = Announcement
    form_class = AnnouncementForm
    template_name = 'admin_panel_app/announcement/create.html'
    success_url = reverse_lazy('admin_panel_app:admin_announcement_list')
    
    def form_valid(self, form):
        context = self.get_context_data()
        image_formset = context['image_formset']

        if form.is_valid() and image_formset.is_valid():
            self.object = form.save(commit=False)
            self.object.owner = form.cleaned_data['owner']
            self.object.slug = slugify(form.cleaned_data['title'])
            self.object.save()

            image_formset.instance = self.object
            image_formset.save()

            return super().form_valid(form)
        else:
            return self.form_invalid(form)
    
    def get_form_kwargs(self):
        kwargs = super(AnnouncementCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        if self.request.POST:
            context['image_formset'] = AnnouncementImageFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['image_formset'] = AnnouncementImageFormSet(instance=self.object)
        
        return context

class AnnouncementUpdateView(LoginRequiredMixin, UpdateView):
    model = Announcement
    form_class = AnnouncementForm
    template_name = 'admin_panel_app/announcement/update.html'
    success_url = reverse_lazy('admin_panel_app:admin_announcement_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        if self.request.POST:
            context['image_formset'] = AnnouncementImageFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['image_formset'] = AnnouncementImageFormSet(instance=self.object)
            
        context['existing_images'] = self.object.images.all()
        
        return context

class AnnouncementDeleteView(LoginRequiredMixin, DeleteView):
    model = Announcement
    template_name = 'admin_panel_app/announcement/delete.html'
    context_object_name = 'announcement'
    success_url = reverse_lazy('admin_panel_app:admin_announcement_list')

class AnnouncementDetailView(LoginRequiredMixin, DetailView):
    model = Announcement
    template_name = 'admin_panel_app/announcement/read.html'
    context_object_name = 'announcement'
    
class AnnouncementListView(LoginRequiredMixin, ListView):
    model = Announcement
    template_name = 'admin_panel_app/announcement/list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['announcements'] = Announcement.objects.all().order_by('pk')
        
        return context
# endregion

# region CarImage views
class AnnouncementImageCreateView(CreateView):
    model = AnnouncementImage
    form_class = AnnouncementImageForm
    template_name = 'admin_panel_app/announcement image/create.html'
    success_url = reverse_lazy('admin_panel_app:admin_announcement_images_list')

class AnnouncementImageUpdateView(LoginRequiredMixin, UpdateView):
    model = AnnouncementImage
    form_class = AnnouncementImageForm
    template_name = 'admin_panel_app/announcement image/update.html'
    success_url = reverse_lazy('admin_panel_app:admin_announcement_images_list')

class AnnouncementImageDeleteView(LoginRequiredMixin, DeleteView):
    model = AnnouncementImage
    template_name = 'admin_panel_app/announcement image/delete.html'
    context_object_name = 'announcement_images'
    success_url = reverse_lazy('admin_panel_app:admin_announcement_images_list')

class AnnouncementImageDetailView(LoginRequiredMixin, DetailView):
    model = AnnouncementImage
    template_name = 'admin_panel_app/announcement image/read.html'
    context_object_name = 'announcement_images'

class AnnouncementImageListView(LoginRequiredMixin, ListView):
    model = AnnouncementImage
    template_name = 'admin_panel_app/announcement image/list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['announcement_images'] = AnnouncementImage.objects.all().order_by('pk')
        
        return context
# endregion

# region Category views
class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'admin_panel_app/category/create.html'
    success_url = reverse_lazy('admin_panel_app:admin_categories_list')

class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'admin_panel_app/category/update.html'
    success_url = reverse_lazy('admin_panel_app:admin_categories_list')

class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = Category
    template_name = 'admin_panel_app/category/delete.html'
    context_object_name = 'category'
    success_url = reverse_lazy('admin_panel_app:admin_categories_list')

class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Category
    template_name = 'admin_panel_app/category/read.html'
    context_object_name = 'category'

class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    template_name = 'admin_panel_app/category/list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all().order_by('pk')
        
        return context
# endregion

# region Favorite views
class FavoriteCreateView(CreateView):
    model = Favorite
    form_class = FavoriteForm
    template_name = 'admin_panel_app/favorite/create.html'
    success_url = reverse_lazy('admin_panel_app:admin_favorites_list')
    
    def form_valid(self, form):
        return super().form_valid(form)

class FavoriteUpdateView(LoginRequiredMixin, UpdateView):
    model = Favorite
    form_class = FavoriteForm

find_house_proj/templates/admin_panel_app/messages/create.html
{% extends "admin_panel_app/base.html" %}
{% load i18n %}

{% block title %}{% trans 'Add Message' %}{% endblock %}

{% block content %}
    {% if user.is_authenticated %}

        {% for field in form %}
            {% if field.errors %}
                <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
                    {{ field.errors.0 }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}

        <div class="col-md-12">
            <div class="card mt-5">
                <div class="card-header bg-orange text-white">
                    <h3 class="card-title mb-0">{% trans 'Add Message' %}</h3>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
            
                        <div class="mb-3">
                            {{ form.chat.label_tag }}
                            {{ form.chat }}
                            <span class="text-muted"><small>{{ form.chat.help_text }}</small></span>
                        </div>
            
                        <div class="mb-3">
                            {{ form.sender.label_tag }}
                            {{ form.sender }}
                            <span class="text-muted"><small>{{ form.sender.help_text }}</small></span>
                        </div>
            
                        <div class="mb-3">
                            {{ form.content.label_tag }}
                            {{ form.content }}
                            <span class="text-muted"><small>{{ form.content.help_text }}</small></span>
                        </div>
            
                        <div class="mb-3">
                            {{ form.is_deleted.label_tag }}
                            {{ form.is_deleted }}
                            <span class="text-muted"><small>{{ form.is_deleted.help_text }}</small></span>
                        </div>
                        <div class="mb-3">
                            {{ form.is_edited.label_tag }}
                            {{ form.is_edited }}
                            <span class="text-muted"><small>{{ form.is_edited.help_text }}</small></span>
                        </div>
            
                        <div class="mb-3">
                            <button type="submit" class="btn btn-orange btn-sm">{% trans 'Add Message' %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    {% else %}
        <h3 class="text-center text-danger">{% trans 'You do not have access to this page !!!' %}</h1>
    {% endif %}

    <div class="mb-3 mt-3">
        <a class="btn btn-red btn-sm" href="{% url 'admin_panel_app:admin_messages_list' %}">{% trans 'Back' %}</a>
    </div>

{% endblock content %}

find_house_proj/templates/admin_panel_app/messages/delete.html
{% extends "admin_panel_app/base.html" %}
{% load i18n %}

{% block title %}{% trans 'Delete Message' %}{% endblock %}

{% block content %}

    {% if user.is_authenticated %}

        <div class="col-md-12">
            <div class="card mt-5">
                <div class="card-header bg-red text-white">
                    <h3 class="card-title mb-0">{% trans 'Delete Message' %}</h3>
                </div>
                <div class="card-body">
                    <div class="alert alert-danger">
                        {% trans 'Warning: This action is irreversible. This data will be permanently deleted.' %}
                    </div>
                    <form method="post">
                        {% csrf_token %}

                        <div class="mb-3">
                            {% trans 'Are you sure you want to delete this message ?' %}
                        </div>
                    
                        <div class="mb-3">
                            <button type="submit" class="btn btn-red btn-sm">{% trans 'Delete Message' %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    {% else %}
        <h3 class="text-center text-danger">{% trans 'You do not have access to this page !!!' %}</h1>
    {% endif %}

    <div class="mb-3 mt-3">
        <a class="btn btn-red btn-sm" href="{% url 'admin_panel_app:admin_messages_list' %}">{% trans 'Back' %}</a>
    </div>

{% endblock content %}

find_house_proj/templates/admin_panel_app/messages/list.html
{% extends "admin_panel_app/base.html" %}

{% load static %}
{% load i18n %}

{% block title %}{% trans 'Messages List' %}{% endblock %}

{% block content %}

    <h3 class="text-center">{% trans 'Messages List' %}</h3>
    <div class="mb-3">
        <input type="text" id="messagesFilterInput" class="custom-form-control" placeholder="Enter filter...">
    </div>
    {% if messages %}
        <div class="table-responsive">
            <table class="table table-hover " data-table="messages">
                <thead>
                    <tr>
                        <th class="text-nowrap">{% trans 'ID' %}</th>
                        <th class="text-nowrap">{% trans 'Chat' %}</th>
                        <th class="text-nowrap">{% trans 'Sender' %}</th>
                        <th class="text-nowrap">{% trans 'Content' %}</th>
                        <th class="text-nowrap">{% trans 'Is deleted' %}</th>
                        <th class="text-nowrap">{% trans 'Is edited' %}</th>
                        <th class="text-nowrap">{% trans 'Date Added' %}</th>
                        <th class="text-nowrap">{% trans 'Edit' %}</th>
                        <th class="text-nowrap">{% trans 'Details' %}</th>
                        <th class="text-nowrap">{% trans 'Delete' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for message in messages %}
                        <tr>
                            <td>{{ message.id }}</td>
                            <td>{{ message.chat }}</td>
                            <td>{{ message.sender }}</td>
                            <td>{{ message.content|truncatechars:100 }}</td>
                            <td>{{ message.is_deleted }}</td>
                            <td>{{ message.is_edited }}</td>
                            <td>{{ message.timestamp }}</td>
                            <td>
                                <a href="{% url 'admin_panel_app:admin_message_update' pk=message.pk %}" class="btn btn-blue btn-sm w-text-75 d-flex align-items-center text-decoration-none">
                                    <img width="20px" height="20px" src="{% static 'users_app/images/icons/profile/edit.svg' %}" alt="{% trans 'Edit' %}" class="mr-1">{% trans 'Edit' %}
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'admin_panel_app:admin_message_read' pk=message.pk %}" class="btn btn-grey btn-sm w-text-75 d-flex align-items-center text-decoration-none">
                                    <img width="20px" height="20px" src="{% static 'users_app/images/icons/profile/details.svg' %}" alt="{% trans 'Details' %}" class="mr-1">{% trans 'Details' %}
                                </a>
                            </td>
                            <td>
                                <a href="{% url 'admin_panel_app:admin_message_delete' pk=message.pk %}" class="btn btn-red btn-sm w-text-75 d-flex align-items-center text-decoration-none">
                                    <img width="20px" height="20px" src="{% static 'users_app/images/icons/profile/delete.svg' %}" alt="{% trans 'Delete' %}" class="mr-1">{% trans 'Delete' %}
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <h3 class="text-center text-danger">{% trans 'You do not have any messages !!!' %}</h3>
    {% endif %}

    <div class="mb-3">
        <a class="btn btn-orange btn-sm" href="{% url 'admin_panel_app:admin_message_create' %}">{% trans 'Add Message' %}</a>
    </div>

    <script src="{% static 'admin_panel_app/js/messages_tables_search.js' %}"></script>
    <script src="{% static 'admin_panel_app/js/table_scroll_script.js' %}"></script>

{% endblock content %}

find_house_proj/templates/admin_panel_app/messages/read.html
{% extends "admin_panel_app/base.html" %}
{% load i18n %}

{% block title %}{% trans 'Message Details' %}{% endblock %}

{% block content %}

    <h3 class="text-center">{% trans 'Message Details' %}</h3>

    <table class="table table-striped">
        <tbody>
            <tr>
                <th>{% trans 'ID' %}</th>
                <td>{{ message.id }}</td>
            </tr>
            <tr>
                <th>{% trans 'Chat' %}</th>
                <td>{{ message.chat }}</td>
            </tr>
            <tr>
                <th>{% trans 'Sender' %}</th>
                <td>{{ message.sender }}</td>
            </tr>
            <tr>
                <th>{% trans 'Content' %}</th>
                <td>{{ message.content }}</td>
            </tr>
            <tr>
                <th>{% trans 'Is deleted' %}</th>
                <td>{{ message.is_deleted }}</td>
            </tr>
            <tr>
                <th>{% trans 'Is edited' %}</th>
                <td>{{ message.is_edited }}</td>
            </tr>
            <tr>
                <th>{% trans 'Date Added' %}</th>
                <td>{{ message.timestamp }}</td>
            </tr>
        </tbody>
    </table>

    <div class="mb-3 mt-3">
        <a class="btn btn-red btn-sm" href="{% url 'admin_panel_app:admin_messages_list' %}">{% trans 'Back' %}</a>
    </div>

{% endblock content %}

find_house_proj/templates/admin_panel_app/messages/update.html
{% extends "admin_panel_app/base.html" %}
{% load i18n %}

{% block title %}{% trans 'Edit Message' %}{% endblock %}

{% block content %}
    {% if user.is_authenticated %}

        {% for field in form %}
            {% if field.errors %}
                <div class="alert alert-danger alert-dismissible fade show mt-3" role="alert">
                    {{ field.errors.0 }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}

        <div class="col-md-12">
            <div class="card mt-5">
                <div class="card-header bg-blue text-white">
                    <h3 class="card-title mb-0">{% trans 'Edit Message' %}</h3>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
            
                        <div class="mb-3">
                            {{ form.chat.label_tag }}
                            {{ form.chat }}
                            <span class="text-muted"><small>{{ form.chat.help_text }}</small></span>
                        </div>
            
                        <div class="mb-3">
                            {{ form.sender.label_tag }}
                            {{ form.sender }}
                            <span class="text-muted"><small>{{ form.sender.help_text }}</small></span>
                        </div>
            
                        <div class="mb-3">
                            {{ form.content.label_tag }}
                            {{ form.content }}
                            <span class="text-muted"><small>{{ form.content.help_text }}</small></span>
                        </div>
            
                        <div class="mb-3">
                            {{ form.is_deleted.label_tag }}
                            {{ form.is_deleted }}
                            <span class="text-muted"><small>{{ form.is_deleted.help_text }}</small></span>
                        </div>
                        <div class="mb-3">
                            {{ form.is_edited.label_tag }}
                            {{ form.is_edited }}
                            <span class="text-muted"><small>{{ form.is_edited.help_text }}</small></span>
                        </div>
            
                        <div class="mb-3">
                            <button type="submit" class="btn btn-blue btn-sm">{% trans 'Edit Message' %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    {% else %}
        <h3 class="text-center text-danger">{% trans 'You do not have access to this page !!!' %}</h1>
    {% endif %}

    <div class="mb-3 mt-3">
        <a class="btn btn-red btn-sm" href="{% url 'admin_panel_app:admin_messages_list' %}">{% trans 'Back' %}</a>
    </div>

{% endblock content %}